# Generated by Django 5.0.7 on 2024-07-23 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240722_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hints',
            field=models.JSONField(default='[]'),
        ),
        migrations.AlterField(
            model_name='question',
            name='problem_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
