# Generated by Django 5.0.7 on 2024-07-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_hints_alter_question_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hints',
            field=models.JSONField(default=list),
        ),
    ]
