# Generated by Django 5.0.7 on 2024-08-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_categories_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(default='javascript', max_length=50),
        ),
    ]
