# Generated by Django 5.0.7 on 2024-09-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
