# Generated by Django 5.0.7 on 2024-09-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userquestionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionprogress',
            name='code_progress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
