# Generated by Django 5.0.7 on 2024-09-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userquestionprogress_code_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionprogress',
            name='failed_tests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userquestionprogress',
            name='passed_tests',
            field=models.JSONField(default=list),
        ),
    ]
